import { writeFileSync } from 'fs';
import { formatAsHtml, L, loadJson } from './utils.mjs';

function generateMiscMarkdown() {
	const pvp = loadJson('GSPvPLeagues');

    let content = `---
title: 'Miscellaneous'
date: '${new Date().toISOString()}'
author: 'AutoGenerated'
---

### Miscellaneous tips collected from the game

${L("Data_Tooltip_DuplicateCrew_Header")}: ${L("Data_Tooltip_DuplicateCrew_Body")}

${L("Data_Tooltip_HeroCollection_Locate_headerText")}: ${L("Data_Tooltip_HeroCollection_Locate_infoText")}

${L("Data_Tooltip_HeroInfo_Level_headerText")}: ${L("Data_Tooltip_HeroInfo_Level_infoText")}

${L("Data_Tooltip_HeroInfo_Power_headerText")}: ${L("Data_Tooltip_HeroInfo_Power_infoText")}

${L("Data_Tooltip_HeroInfo_Rank_headerText")}: ${L("Data_Tooltip_HeroInfo_Rank_infoText")}

${L("Data_Tooltip_HeroInfo_Rarity_headerText")}: ${L("Data_Tooltip_HeroInfo_Rarity_infoText")}

${L("Data_Tooltip_HeroInfo_Role_headerText")}: ${L("Data_Tooltip_HeroInfo_Role_infoText")}

${L("Data_Tooltip_HeroInfo_Tags_headerText")}: ${L("Data_Tooltip_HeroInfo_Tags_infoText")}

${L("Common_AccessoryStat_Attack")}: ${L("Data_Tooltip_HeroInfo_Stats_Attack_infoText")}

${L("Common_AccessoryStat_CritChance")}: ${L("Data_Tooltip_HeroInfo_Stats_CritChance_infoText")}

${L("Common_AccessoryStat_CritDamage")}: ${L("Data_Tooltip_HeroInfo_Stats_CritDamage_infoText")}

${L("Common_AccessoryStat_Defence")}: ${L("Data_Tooltip_HeroInfo_Stats_Defense_infoText")}

${L("Common_AccessoryStat_GlancingChance")}: ${L("Data_Tooltip_HeroInfo_Stats_GlancingChance_infoText")}

${L("Common_AccessoryStat_GlancingDamage")}: ${L("Data_Tooltip_HeroInfo_Stats_GlancingDamage_infoText")}

${L("Common_AccessoryStat_Health")}: ${L("Data_Tooltip_HeroInfo_Stats_Health_infoText")}

${L("Common_AccessoryStat_Resolve")}: ${L("Data_Tooltip_HeroInfo_Stats_Resolve_infoText")}

${L("Common_AccessoryStat_Speed")}: ${L("Data_Tooltip_HeroInfo_Stats_Speed_infoText")}

${L("Common_AccessoryStat_Tech")}: ${L("Data_Tooltip_HeroInfo_Stats_Tech_infoText")}

${L("Data_Tooltip_PlayerProfile_Level_headerText")}: ${L("Data_Tooltip_PlayerProfile_Level_infoText")}

${L("Data_Tooltip_PlayerProfile_PVPLeague_headerText")}: ${L("Data_Tooltip_PlayerProfile_PVPLeague_infoText")}

${L("Data_Tooltip_TeamSelect_Proficiency_Command_headerText")}: ${L("Data_Tooltip_TeamSelect_Proficiency_Command_infoText")}

${L("Data_Tooltip_TeamSelect_Proficiency_Engineering_headerText")}: ${L("Data_Tooltip_TeamSelect_Proficiency_Engineering_infoText")}

${L("Data_Tooltip_TeamSelect_Proficiency_Medical_headerText")}: ${L("Data_Tooltip_TeamSelect_Proficiency_Medical_infoText")}

${L("Data_Tooltip_TeamSelect_Proficiency_Science_headerText")}: ${L("Data_Tooltip_TeamSelect_Proficiency_Science_infoText")}

${L("Data_Tooltip_TeamSelect_Proficiency_Security_headerText")}: ${L("Data_Tooltip_TeamSelect_Proficiency_Security_infoText")}

${L("Data_Tooltip_TeamSelect_TeamPower_infoText")}

### ${L("Data_StoreCategory_NexusParticles")}

${L("Data_Tooltip_NexusParticle_Level_headerText")}: ${L("Data_Tooltip_NexusParticle_Level_infoText")}

${L("Data_Tooltip_NexusParticle_Rarity_headerText")}: ${formatAsHtml(L("Data_Tooltip_NexusParticle_Rarity_infoText"))}

${L("Data_Tooltip_NexusParticle_Tags_headerText")}: ${L("Data_Tooltip_NexusParticle_Tags_infoText")}


### Loading screen tips

${L("LoadingTips_01")}

${L("LoadingTips_02")}

${L("LoadingTips_03")}

${L("LoadingTips_04")}

${L("LoadingTips_05")}

${L("LoadingTips_06")}

${L("LoadingTips_07")}

${L("LoadingTips_08")}

${L("LoadingTips_09")}

${L("LoadingTips_10")}

${L("LoadingTips_11")}

${L("LoadingTips_12")}

${L("LoadingTips_13")}

${L("LoadingTips_14")}

${L("LoadingTips_15")}

${L("LoadingTips_16")}

${L("LoadingTips_17")}


`;

    writeFileSync(new URL(`../_wiki/misc.md`, import.meta.url), content);
}

export { generateMiscMarkdown };
