import { writeFileSync } from 'fs';
import { L, loadJson } from './utils.mjs';

function mapDifficulty(difficulty) {
	if (difficulty.toLowerCase() == 'doom') {
		return 'UI_Common_Difficulty_Expert';
	} else if (difficulty.toLowerCase() == 'hard') {
		return 'UI_Common_Difficulty_Advanced';
	} else if (difficulty.toLowerCase() == 'easy') {
		return 'UI_Common_Difficulty_Normal';
	} else {
		console.warn(`Unknown difficulty '${difficulty}'`);
		return 'UI_Common_Difficulty_Normal';
	}
}

function formatRewardList(rewards) {
    let result = [];
    for (let name in rewards) {
        result.push(`${name} x${rewards[name]}`);
    }

    return result.join(', ');
}

function generateShuttlesMarkdown() {
	const shuttles = loadJson('GSShuttlecraft');
    const missions = loadJson('GSMissions');
    const episodes = loadJson('GSEpisodes');

	let content = `---
title: 'Shuttlecrafts'
date: '${new Date().toISOString()}'
author: 'AutoGenerated'
---

`;

	Object.values(shuttles).forEach((shuttle) => {
        let unlockMission = missions[`${shuttle.m_UnlockMission.id}-${shuttle.m_UnlockMission.difficulty}`];
        let unlockEpisode = episodes[`${unlockMission.EpisodeId}-${shuttle.m_UnlockMission.difficulty}`];

		content += `
### ${L('UI_Shuttlecraft_Mission_Title').replace('{0}', shuttle.m_RouteNumber)} (${L('UI_Mission_Episode_X').replace('{0}', shuttle.m_EpisodeNumber)})
<img src="/assets/MapNode_Image_Shuttle.png" alt="Shuttlecraft" height="32" >

Difficulty: **${L(mapDifficulty(shuttle.m_Difficulty))}**

Duration: **${shuttle.m_Duration}**

Unlocks after completing mission ${L(unlockMission.Name)} (episode ${unlockEpisode.OrderIndex} - ${L(unlockEpisode.Name)}) on ${L(mapDifficulty(shuttle.m_UnlockMission.difficulty))} difficulty.

Max jackpot chance power: **${shuttle.m_MaxJackpotChancePower}**

Base rewards: **${formatRewardList(shuttle.m_BaseReward.AllItems)}**

Jackpot rewards: **${formatRewardList(shuttle.m_JackpotReward.AllItems)}**
`;
	});

	writeFileSync(new URL(`../_wiki/shuttles.md`, import.meta.url), content);
}

export { generateShuttlesMarkdown };
